version: "3"
# The service list for docker container group
services:
  webapp:
    # the build information for docker run command
    build:
      # the path for dockerfile
      context: .
      # the name of docker file
      dockerfile: Dockerfile
    # the environment setting should be set in same level with build
    # environment:
    #   RAILS_ENV: development
    #   POSTGRES_HOST: db_postgres
    #   POSTGRES_USER: tester
    #   POSTGRES_PASSWORD: 111111abcdef
    #   POSTGRES_PORT: 5432
    
    command:
        # --poll=2000 is needed to make local connecting container
        ng serve --host 0.0.0.0 --poll=2000
    # the value is the tag information for the image when execute the [docker run] command with Dockerfile
    # It should be existed with build information
    image: angularcli-dev:1.0
    ports:
      - 4200:4200
    volumes:
      - .:/StudyAngular
    # express dependency between services, it means the services in [depends_on] will be started before the service
    # depends_on:
      # the dependency services should be defined as a list
      # - 

# volumes:
#   pg-data:
#     driver: local